service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::kostyakulak-import-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::kostyakulak-import-service/*"

functions:
  importProductsFile:
    handler: api/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: api/importFileParser.importFileParser
    events:
      - s3:
          bucket: kostyakulak-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: 'uploaded/'
            - suffix: ''
          existing: true
